name: rsd
channels:
- defaults
dependencies:
- bleach=2.0.0
- ca-certificates=2017.08.26
- certifi=2017.7.27.1
- dbus=1.10.22
- decorator=4.1.2
- entrypoints=0.2.3
- expat=2.2.5
- fontconfig=2.12.4
- freetype=2.8
- glib=2.53.6
- gmp=6.1.2
- gst-plugins-base=1.12.2
- gstreamer=1.12.2
- html5lib=0.999999999
- icu=58.2
- ipykernel=4.6.1
- ipython=6.1.0
- ipython_genutils=0.2.0
- ipywidgets=7.0.0
- jedi=0.10.2
- jinja2=2.9.6
- jpeg=9b
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.1.0
- jupyter_console=5.2.0
- jupyter_core=4.3.0
- libedit=3.1
- libffi=3.2.1
- libgcc-ng=7.2.0
- libpng=1.6.32
- libsodium=1.0.15
- libstdcxx-ng=7.2.0
- libxcb=1.12
- libxml2=2.9.4
- markupsafe=1.0
- mistune=0.8.1
- nbconvert=5.3.1
- nbformat=4.4.0
- ncurses=6.0
- notebook=5.2.1
- openssl=1.0.2m
- pandoc=1.19.2.1
- pandocfilters=1.4.2
- pcre=8.41
- pexpect=4.2.1
- pickleshare=0.7.4
- pip=9.0.1
- prompt_toolkit=1.0.15
- ptyprocess=0.5.2
- pygments=2.2.0
- pyqt=5.6.0
- python=3.6.3
- python-dateutil=2.6.1
- pyzmq=16.0.2
- qt=5.6.2
- qtconsole=4.3.1
- readline=7.0
- setuptools=36.5.0
- simplegeneric=0.8.1
- sip=4.18.1
- six=1.11.0
- sqlite=3.20.1
- terminado=0.6
- testpath=0.3.1
- tk=8.6.7
- tornado=4.5.2
- traitlets=4.3.2
- wcwidth=0.1.7
- webencodings=0.5.1
- wheel=0.29.0
- widgetsnbextension=3.0.2
- xz=5.2.3
- zeromq=4.2.2
- zlib=1.2.11
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - markdown==2.6.9
  - prompt-toolkit==1.0.15
  - py==1.5.2
  - pytest==3.2.5
prefix: /home/vince/anaconda3/envs/rsd

